services:
  - type: web
    name: crawler-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: uvicorn app.crawler_api:app --host 0.0.0.0 --port 8000
